"use client";

import { useEffect, useRef } from 'react';
import { usePathname } from 'next/navigation';
import { db } from '@/lib/firebase';
import { doc, onSnapshot, setDoc } from 'firebase/firestore';
import { useBookStore } from '@/app/store/bookStore';

export default function FirebaseSync() {
  const pathname = usePathname();
  const isTeacher = pathname?.includes('/rehab-elsibai');
  
  // Ref to prevent echo loops when updating Zustand from Firebase
  const isUpdatingFromFirebase = useRef(false);

  useEffect(() => {
    // We store curriculum and zones in main doc, pages in separate docs
    const docRef = doc(db, 'curriculums', 'main');
    let timeoutId: NodeJS.Timeout;
    let unsubStore: () => void;
    let studentPagesUnsub: () => void;

    // 1. ALWAYS listen to Firebase main doc
    const unsubscribeSnapshot = onSnapshot(docRef, (snapshot) => {
      if (snapshot.exists()) {
        const data = snapshot.data();
        const localState = useBookStore.getState();
        
        const remoteHasData = Object.keys(data.curriculum || {}).length > 0;
        const localHasData = Object.keys(localState.curriculum || {}).length > 0;
        
        if (!remoteHasData && localHasData) {
          if (isTeacher) {
            setDoc(docRef, {
              curriculum: localState.curriculum || {},
              zones: localState.zones || []
            }, { merge: true });
          }
          return;
        }

        isUpdatingFromFirebase.current = true;
        
        useBookStore.setState({
          curriculum: data.curriculum || {},
          zones: data.zones || []
        });
        
        setTimeout(() => {
          isUpdatingFromFirebase.current = false;
        }, 500);
      }
    });

    // 2. Fetch specific lesson's pages (For BOTH Teacher and Student)
    const fetchLessonPages = (lessonId: string) => {
      if (studentPagesUnsub) studentPagesUnsub();
      console.log('[Sync] Fetching pages for lesson:', lessonId);
      studentPagesUnsub = onSnapshot(doc(db, 'curriculums', `pages_${lessonId}`), (snap) => {
        if (snap.exists()) {
          const lessonPages = snap.data().pages || [];
          const currentState = useBookStore.getState();
          // Merge remote pages for this lesson with local pages for other lessons
          const otherPages = currentState.pages.filter(p => p.lessonId !== lessonId);
          const newPages = [...otherPages, ...lessonPages];
          
          // Only update if there's an actual change to avoid infinite loops
          if (JSON.stringify(currentState.pages) !== JSON.stringify(newPages)) {
            isUpdatingFromFirebase.current = true;
            useBookStore.setState({ pages: newPages });
            setTimeout(() => { isUpdatingFromFirebase.current = false; }, 500);
          }
        }
      });
    };

    // Subscribe to lesson changes
    unsubStore = useBookStore.subscribe((state, prevState) => {
      if (state.activeLessonId !== prevState.activeLessonId && state.activeLessonId) {
        console.log('[Sync] Lesson changed to:', state.activeLessonId);
        fetchLessonPages(state.activeLessonId);
      }
      
      // 3. If Teacher, push local changes UP
      if (isTeacher && !isUpdatingFromFirebase.current) {
        clearTimeout(timeoutId);
        timeoutId = setTimeout(() => {
          
          // Auto-purge any old placeholder images that were generated by the previous limit
          const cleanPages = (state.pages || []).filter(p => !p.imageUrl?.includes('via.placeholder.com'));
          
          const cleanZones = (state.zones || []).map(z => {
            const newZ = { ...z, content: { ...z.content } };
            if (newZ.content.videoUrl && newZ.content.videoUrl.length > 100000) {
              newZ.content.videoUrl = "";
            }
            if (newZ.content.audioUrl && newZ.content.audioUrl.length > 100000) {
              newZ.content.audioUrl = "";
            }
            return newZ;
          });

          // Function to auto-migrate huge base64 to Cloudinary
          const uploadBase64ToCloudinary = async (base64Str: string): Promise<string> => {
            try {
              const formData = new FormData();
              formData.append('file', base64Str);
              formData.append('upload_preset', 'bqwntt08');
              const res = await fetch(`https://api.cloudinary.com/v1_1/hruezreb/auto/upload`, {
                method: 'POST',
                body: formData
              });
              const data = await res.json();
              if (data && data.secure_url) {
                return data.secure_url;
              }
            } catch (e) {
              console.error("Auto-upload failed", e);
            }
            return base64Str;
          };

          // Auto-migrate large base64 images to Cloudinary to avoid 1MB Firebase limit
          const migrateData = async () => {
            let stateChanged = false;
            
            for (let i = 0; i < cleanPages.length; i++) {
              if (cleanPages[i].imageUrl && cleanPages[i].imageUrl.startsWith('data:image/') && cleanPages[i].imageUrl.length > 50000) {
                console.log(`[Sync] Auto-migrating large page image to Cloudinary...`);
                cleanPages[i].imageUrl = await uploadBase64ToCloudinary(cleanPages[i].imageUrl);
                stateChanged = true;
              }
            }

            for (let i = 0; i < cleanZones.length; i++) {
              if (cleanZones[i].content?.imageUrl && cleanZones[i].content.imageUrl!.startsWith('data:image/') && cleanZones[i].content.imageUrl!.length > 50000) {
                console.log(`[Sync] Auto-migrating large zone image to Cloudinary...`);
                cleanZones[i].content.imageUrl = await uploadBase64ToCloudinary(cleanZones[i].content.imageUrl!);
                stateChanged = true;
              }
            }

            if (stateChanged) {
              useBookStore.setState({ pages: cleanPages, zones: cleanZones });
            }

            const needsHealing = JSON.stringify(state.pages) !== JSON.stringify(cleanPages) || JSON.stringify(state.zones) !== JSON.stringify(cleanZones);
            if (needsHealing && !stateChanged) {
              useBookStore.setState({ pages: cleanPages, zones: cleanZones });
            }

            // Save main doc
            const dataToSave = {
              curriculum: state.curriculum || {},
              zones: cleanZones
            };
            
            const mainSize = JSON.stringify(dataToSave).length;
            console.log(`[Sync] Saving main doc. Size: ${(mainSize / 1024).toFixed(2)} KB`);
            
            setDoc(docRef, dataToSave, { merge: true }).catch(err => {
              console.error(err);
              alert("خطأ خطير: فشل حفظ التعديلات! مساحة المنهج ممتلئة جداً (أكثر من 1 ميجابايت). يرجى مسح بعض التفاعلات القديمة.");
            });

            // Save pages PER LESSON
            const allLessonIds = Object.values(state.curriculum || {}).flatMap(units => (units as any[]).flatMap(u => u.lessons.map((l:any) => l.id)));
            allLessonIds.forEach(lId => {
              const lPages = cleanPages.filter(p => p.lessonId === lId);
              const pagesSize = JSON.stringify({ pages: lPages }).length;
              
              if (lPages.length > 0) {
                  console.log(`[Sync] Saving pages for lesson ${lId}. Size: ${(pagesSize / 1024).toFixed(2)} KB`);
              }

              setDoc(doc(db, 'curriculums', `pages_${lId}`), { pages: lPages }, { merge: true }).catch(err => {
                  console.error(err);
                  alert("خطأ خطير: فشل حفظ الصور في هذا الدرس! حجم الصور القديمة كبير جداً. يرجى مسح الصور القديمة وإعادة رفعها.");
              });
            });
            
            // Save unassigned pages just in case
            const unassignedPages = cleanPages.filter(p => !p.lessonId);
            if (unassignedPages.length > 0) {
              setDoc(doc(db, 'curriculums', `pages_unassigned`), { pages: unassignedPages }, { merge: true });
            }
          };

          migrateData();


        }, 1500);
      }
    });

    // Trigger initial load if activeLessonId is already set
    const initialLesson = useBookStore.getState().activeLessonId;
    if (initialLesson) {
      console.log('[Sync] Initial lesson load:', initialLesson);
      fetchLessonPages(initialLesson);
    }


    
    return () => {
      unsubscribeSnapshot();
      if (unsubStore) unsubStore();
      if (studentPagesUnsub) studentPagesUnsub();
      clearTimeout(timeoutId);
    };
  }, [isTeacher]);

  return null; // This component has no UI, it works silently in the background
}
